version: "3.9"

services:
  inventory_db:
    image: mysql:8.3.0
    container_name: mysql_inventory_service
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: inventory_service
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass

    ports:
      - "3307:3306"
    volumes:
      - inventory_service_db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  inventory_service_db_data: {} # USE A NEW VOLUME
